vich_uploader:
    db_driver: orm

    mappings:
        rechnungen:
            uri_prefix:         '%app.path.rechnungen%'
            upload_destination: '%kernel.project_dir%/public%app.path.rechnungen%'
